services:
  # Backend Node.js service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend

  # MongoDB database service
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  # Mongo Express (GUI for MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - backend

  # Nginx for reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
